services:
  
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduinsight
      MYSQL_USER: eduinsight_user
      MYSQL_PASSWORD: eduinsight_pass
      TZ: Asia/Manila
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: