services:
  cloudflaretunnel:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTI0MGY5M2ZkOGEzNzg1NTdhZmFhZjFkZTY3ZDcyNDYiLCJ0IjoiOTRlYmMxNmUtODExZS00M2ZiLTllYWQtZGIzNzE5YTY4YzZlIiwicyI6Ik1XRTNaamN5TW1JdE1qVm1NaTAwTVRnd0xUa3lOekF0TW1Sa1pqRmhOams1TldFeSJ9
    command: tunnel --no-autoupdate run
    networks:
      - eduinsight_network

  eduinsight:
    container_name: nextjs
    build:
      context: .
    image: eduinsight:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://eduinsight_user:eduinsight_pass@mysql:3306/eduinsight
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - eduinsight_network

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduinsight
      MYSQL_USER: eduinsight_user
      MYSQL_PASSWORD: eduinsight_pass
      TZ: Asia/Manila
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eduinsight_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    networks:
      - eduinsight_network

  socket:
    container_name: socket
    restart: unless-stopped
    # the path of directory for build
    build:
      context: ./server
      dockerfile: Dockerfile
    image: socket:latest
    #env_file: /server/.env
    # the changes in my local will be reflected into container (development only)
    volumes:
      - ./server:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "4000:4000"      # Socket API
      - "9001:9001"      # Socket WS
    expose:
      # internal ports
      - "4000"
    environment:
      NODE_ENV: development
      SERVER_PORT: 4000 
    networks:
      - eduinsight_network

  portainer: 
    container_name: portainer
    image: portainer/portainer
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Asia/Manila
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    networks:
      - eduinsight_network
      
volumes:
  mysql_data:

networks:
  eduinsight_network:
    driver: bridge
