services:

  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
        - PANGOLIN_ENDPOINT=https://proxy.eduinsight.systems
        - NEWT_ID=bv0qm2maokiw08s
        - NEWT_SECRET=bd2bxb1z37fqz5m8p2rozltta3cix89qfrsurq9evtlbipaw
    networks:
    - eduinsight_network

  eduinsight:
    container_name: nextjs
    build:
      context: .
    image: eduinsight:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/eduinsight
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - eduinsight_network

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: eduinsight
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Manila
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eduinsight_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    networks:
      - eduinsight_network

  peer:
    container_name: peer
    restart: unless-stopped
    build:
      context: ./peer
      dockerfile: Dockerfile
    image: peer:latest
    volumes:
      - ./peer:/usr/src/app
    ports:
      - "9001:9001"  
    expose:
      - "9001"
    environment:
      NODE_ENV: development
      SERVER_PORT: 9001 
    networks:
      - eduinsight_network

  socket:
    container_name: socket
    restart: unless-stopped
    # the path of directory for build
    build:
      context: ./server
      dockerfile: Dockerfile
    image: socket:latest
    #env_file: /server/.env
    # the changes in my local will be reflected into container (development only)
    volumes:
      - ./server:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "4000:4000"      # Socket API
    expose:
      # internal ports
      - "4000"
    environment:
      NODE_ENV: development
      SERVER_PORT: 4000 
    networks:
      - eduinsight_network

  portainer: 
    container_name: portainer
    image: portainer/portainer
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Asia/Manila
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    networks:
      - eduinsight_network
      
volumes:
  mysql_data:

networks:
  eduinsight_network:
    driver: bridge
